version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 19
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - docker build -t sample .
