version: 0.1

phases:
  install:
    runtime-versions:
      maven: 3.8.5-openjdk-17
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - docker build -t sample .
